### ISSUE TITLE
Class 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter' not found

### ISSUE THREAD

**Issue by CWallenberg** [tymondesigns/jwt-auth#1326]
```php
[Symfony\Component\Debug\Exception\FatalThrowableError]
Class 'Tymon\JWTAuth\Providers\JWT\NamshiAdapter' not found
```
The class is named Namshi.php instead of NamshiAdapter.php.

**Comment by Punksolid** [comment]
Where/how did you fixed it?

**Comment by CWallenberg** [comment]
I realized that I was using and old version of the config file. Deleted the old version of the config file and published the new one and it worked.

**Comment by angel8731** [comment]
find you jwt.php of config file, update three part 
1.  'jwt' => 'Tymon\JWTAuth\Providers\JWT\Namshi',
2. 'auth' => 'Tymon\JWTAuth\Providers\Auth\Illuminate',
3. 'storage' => 'Tymon\JWTAuth\Providers\Storage\Illuminate' 
i have fixed it and it worked

**Comment by dragoscirjan** [comment]
This still happens with v-1.0.0-RC2. Perhaps revise `php artisan vendor:publish --provider="Tymon\JWTAuth\Providers\JWTAuthServiceProvider"` routine

**Comment by adelsedighi** [comment]
angel8731 commented on Oct 11, 2017 fixed my error thank you

**Comment by lava0208** [comment]
Good article.

**Comment by dev-techguy** [comment]
|-_-| Thanks

**Comment by qadeermuniry** [comment]
> find you jwt.php of config file, update three part
> 
> 1. 'jwt' => 'Tymon\JWTAuth\Providers\JWT\Namshi',
> 2. 'auth' => 'Tymon\JWTAuth\Providers\Auth\Illuminate',
> 3. 'storage' => 'Tymon\JWTAuth\Providers\Storage\Illuminate'
>    i have fixed it and it worked

updated these three parts and running composer update worked

**Comment by KotaOHARAZAWA** [comment]
thx :)
