### ISSUE TITLE
Cannot Invalidate Token

### ISSUE THREAD

**Issue by re1naldo** [tymondesigns/jwt-auth#1458]
I use dev-develop branch and after following the [Quick Start guide](http://jwt-auth.readthedocs.io/en/docs/quick-start/), login and access permission work well. The only problem is token cannot be invalidated even after `$this→guard()→logout()` is called. I logged out and tried using the old token, but it’s still valid.

Blacklist-related attributes have been set:
```
'blacklist_enabled' => env('JWT_BLACKLIST_ENABLED', true),
'blacklist_grace_period' => env('JWT_BLACKLIST_GRACE_PERIOD', 0),
```

How to invalidate token? Do we need to call other methods besides `logout()`?

**Comment by tymondesigns** [comment]
@re1naldo Could you pull again, this may have been fixed as part of another issue

**Comment by re1naldo** [comment]
@tymondesigns Thanks for the update, but this issue still exists.

**Comment by tymondesigns** [comment]
I've just checked this myself, and it works for me. I suspect that you have `JWT_BLACKLIST_ENABLED` or `JWT_BLACKLIST_GRACE_PERIOD` somewhere in your env file

**Comment by re1naldo** [comment]
I didn’t see `JWT_BLACKLIST_ENABLED` or `JWT_BLACKLIST_GRACE_PERIOD` in my .env file. Is there other configuration that is related to this issue?

**Comment by re1naldo** [comment]
Token can be invalidated after `CACHE_DRIVER` is set to `file`.
