### ISSUE TITLE
use JWTAuth Undefine Class

### ISSUE THREAD

**Issue by preciouslogic** [tymondesigns/jwt-auth#533]
Hi,

I have follow the whole process from the document but in the end when i try to use

use JWTAuth;
use Tymon\JWTAuth\Exceptions\JWTException;

it show that there are no classes or undefined classes kindly solve my issue. I am using laravel 5.2.19 version and this is very disturbing situation.

thanks

**Comment by mallardduck** [comment]
This doesn't sound like an issue we can solve for you, this seems like an issue that could be caused my multiple things; the root of them being a misunderstanding on how it should be setup.

If you've gotten the package with composer properly and the composer autoloader is being used correctly, then it should be able to find those classes in the package. Knowing what JWT package version your own might help as well, since you've only told us the Laravel version.

Additionally, If you actually paste us the error you've been shown, then we maybe able to assist you further; providing us some relevant information, other than you telling us you have an issue and you want it fixed, might give us the context needed to assist you.

As it stands there's simply not enough information for us to work from here.

**Comment by preciouslogic** [comment]
Thank for quick response i have attach the screen shot of all of my steps with error kindly take a look.

![img_4304](https://cloud.githubusercontent.com/assets/6730214/13170071/e9f85dc2-d702-11e5-8ff1-afe13c7a80b2.JPG)
![img_4305](https://cloud.githubusercontent.com/assets/6730214/13170067/e85d9efa-d702-11e5-86e3-4118c767be1e.JPG)
![img_4307](https://cloud.githubusercontent.com/assets/6730214/13170068/e8a0b50a-d702-11e5-890a-ba4c1e53e870.JPG)
![img_4308](https://cloud.githubusercontent.com/assets/6730214/13170069/e9474f5a-d702-11e5-93be-60233cfc686a.JPG)
![img_4309](https://cloud.githubusercontent.com/assets/6730214/13170070/e968e480-d702-11e5-96ff-f3f375bbc7b1.JPG)

**Comment by mallardduck** [comment]
Hey, this might help next time you need screenshots: https://support.apple.com/en-us/HT201361

At this point I'm still not sure, but if you haven't you may want to try this out. Change this:
```
use JWTAuth;
```


To:
```
use Tymon\JWTAuth\JWTAuth;
```

**Comment by preciouslogic** [comment]
Still getting the same error not library detect or found.
<img width="1616" alt="screen shot 2016-02-19 at 2 00 01 pm" src="https://cloud.githubusercontent.com/assets/6730214/13172365/26d0a37c-d711-11e5-9b2b-d06896b77c33.png">

**Comment by tymondesigns** [comment]
try adding the service provider above your app specific ones, as seen here

![screen shot 2016-02-19 at 23 27 03](https://cloud.githubusercontent.com/assets/1801923/13192079/71eb7590-d760-11e5-90b4-e5ef70cdad55.png)

**Comment by tymondesigns** [comment]
However ignore the fact that the service provider path is different here (this example uses the dev branch)

**Comment by tymondesigns** [comment]
I'll assume this is resolved?

**Comment by preciouslogic** [comment]
noop it was not resolved  as i am just not using it any more. I tried every possible step to resolve but no use so it good that ticket should be close as it is nota problem to me any more :)

**Comment by ratanakpek** [comment]
same error as me, did anyone find out?
