### ISSUE TITLE
lumen 5.3 - Argument 1 passed to Tymon\JWTAuth\Providers\Storage\Illuminate::__construct() must be an instance of Illuminate\Contracts\Cache\Repository, none given

### ISSUE THREAD

**Issue by olivecashlez** [tymondesigns/jwt-auth#987]
I'm using lumen 5.3 and I got this error : 
`ErrorException in Illuminate.php line 40:
Argument 1 passed to Tymon\JWTAuth\Providers\Storage\Illuminate::__construct() must be an instance of Illuminate\Contracts\Cache\Repository, none given, called in /var/www/html/api-lumen/vendor/tymon/jwt-auth/src/Providers/AbstractServiceProvider.php on line 321 and defined`

**Comment by tymondesigns** [comment]
this has been fixed... run composer update again

**Comment by olivecashlez** [comment]
@tymondesigns still can not, I still get the same error after run composer update.
